version: 0.2

phases:
   install:
        runtime-versions:
            dotnet: 6.0

   pre_build:
        commands:
            - echo "current path"
            - pwd
            - cd ${CODEBUILD_SRC_DIR}/CodePipline/DeployLambda  # CODEBUILD_SRC_DIR => AWS Codebuild 環境變數

   build:
        commands:
            - dotnet restore
            - dotnet publish -p:PublishReadyToRun=false -c Release -o ./output
            
artifacts:
   files:
      - ${CODEBUILD_SRC_DIR}/CodePipline/DeployLambda/output/**/*
